# loop for VMs in each VM type
- name: Create Snapshot for VMs in {{cluster_type}} - {{vm_type.type}}
  include_tasks: create_snapshot-tasks.yaml
  loop: "{{vm_type.vms}}"
  loop_control:
    loop_var: vm
