kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: nginx-test
  name: nginx-test
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 32003
  selector:
    app: nginx-test