- name: Set kubeadm-config.yaml
  become: yes
  template:
    src: files/kubeadm-config.yaml
    dest: /root/kubeadm-config.yaml
  when: inventory_hostname==first_master.ip_addr
- name: Stat kubeadm
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubeadm_stat
  when: inventory_hostname==first_master.ip_addr
- name: Init kubeadm
  become: yes
  shell: kubeadm init --config /root/kubeadm-config.yaml
  when: inventory_hostname==first_master.ip_addr and not kubeadm_stat.stat.exists
- name: Apply flannel
  become: yes
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/c5d10c8/Documentation/kube-flannel.yml
  when: inventory_hostname==first_master.ip_addr and not kubeadm_stat.stat.exists
- name: Archive certs
  become: yes
  archive:
    format: zip
    path: /etc/kubernetes/pki
    dest: /root/certs.zip
  when: inventory_hostname==first_master.ip_addr
- name: Fetch certs
  become: yes
  fetch:
    src: /root/certs.zip
    dest: files/certs
  when: inventory_hostname==first_master.ip_addr
- name: Move certs
  local_action: command mv {{playbook_dir}}/files/certs/{{inventory_hostname}}/root/certs.zip {{playbook_dir}}/files/certs/
  when: inventory_hostname==first_master.ip_addr
- name: Fetch conf
  become: yes
  fetch:
    src: /etc/kubernetes/admin.conf
    dest: files/conf
  when: inventory_hostname==first_master.ip_addr
- name: Move conf
  local_action: command mv {{playbook_dir}}/files/conf/{{inventory_hostname}}/etc/kubernetes/admin.conf {{playbook_dir}}/files/conf/
  when: inventory_hostname==first_master.ip_addr
