- name: Set kubeadm-config.yaml
  become: yes
  template:
    src: "{{playbook_dir}}/files/kubeadm-config.third.yaml"
    dest: /root/kubeadm-config.yaml
  when: inventory_hostname==third_master.ip_addr
- name: Send conf
  become: yes
  copy:
    src: "{{playbook_dir}}/files/conf/admin.conf"
    dest: /etc/kubernetes/admin.conf
  when: inventory_hostname==third_master.ip_addr
- name: Send and extract certs
  become: yes
  unarchive:
    src: "{{playbook_dir}}/files/certs/certs.zip"
    dest: /etc/kubernetes/
  when: inventory_hostname==third_master.ip_addr
- name: Find unnecessary certs
  find:
    paths: /etc/kubernetes/pki/
    patterns: "apiserver*,front-proxy-client*"
  register: find_results
  when: inventory_hostname==third_master.ip_addr
- name: Remove unnecessary certs
  become: yes
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ find_results['files'] }}"
  when: inventory_hostname==third_master.ip_addr
- name: Find unnecessary certs for etcd
  find:
    paths: /etc/kubernetes/pki/etcd/
    patterns: "healthcheck*,peer*,server*"
  register: find_results
  when: inventory_hostname==third_master.ip_addr
- name: Remove unnecessary certs for etcd
  become: yes
  file:
    path: "{{ item['path'] }}"
    state: absent
  with_items: "{{ find_results['files'] }}"
  when: inventory_hostname==third_master.ip_addr

