# create or update cloud init for each vm
- name: Hash password for - {{cluster_type}} - {{vm_type.type}} - {{vm.name}}
  shell: mkpasswd --method=SHA-512 --rounds=4096 {{vm_type.password}}
  register: hashed_password
- name: Create/Update cloud config file for - {{cluster_type}} - {{vm_type.type}} - {{vm.name}}
  template: src=templates/cloud-config.j2 dest={{work_dir}}/cloud_config_{{cluster_type}}_{{vm_type.type}}_{{vm.name}}
- name: Create/Update network config file for - {{cluster_type}} - {{vm_type.type}} - {{vm.name}}
  template: src=templates/network-config.j2 dest={{work_dir}}/network_config_{{cluster_type}}_{{vm_type.type}}_{{vm.name}}
- name: Create/Update cloud init disk image from file for - {{cluster_type}} - {{vm_type.type}} - {{vm.name}}
  shell: cloud-localds --network-config={{work_dir}}/network_config_{{cluster_type}}_{{vm_type.type}}_{{vm.name}} {{work_dir}}/cloud_config_{{cluster_type}}_{{vm_type.type}}_{{vm.name}}.cdrom {{work_dir}}/cloud_config_{{cluster_type}}_{{vm_type.type}}_{{vm.name}}
